### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by YTCuber** [YTCuber/HTTimer-4.2-Alpha#1]
- [ ] German translations
- [ ] Top 10 Graph, DNF% Graph, How often you solved when Graph, Best Single Text, Best Ao5 Text, Best Ao12 Text, Last Scramble Text, Current Goals %, Best Goals %, Inspection Time, Inspection, Draw Scramble Graphic, % of Current WR/CR Graph
- [ ] Be able to add Comment, Reconstruction, Method, FMC Solution  for every solve time
- [ ] 3x3 Noobs, CLL, ELL, Edges-only, Corners-only, EG, LSLL scramblers
- [ ] Import from QQTimer
- [x] Improve AlgSets, Goals
- [ ] Change Layout font size option
- [x] Begin documentation
- [ ] Auto-Save option
- [x] Use small font after decimal point option
